version: 2
jobs:
  build:
    working_directory: ~/project
    docker:
      - image: node:8
    steps:
      - checkout
      - restore_cache:
          key: node_modules-{{ checksum "package-lock.json" }}
      - run:
          name: Install dependencies
          command: npm install --unsafe-perm
      - run:
          name: Rebuild problematic node modules
          command: npm rebuild node-sass phantomjs-prebuilt
      - save_cache:
          name: Save cache (node_modules)
          key: node_modules-{{ checksum "package-lock.json" }}
          paths:
            - node_modules/
      - run:
          name: Build
          command: npm run build
      - store_artifacts:
          path: dist/
      - deploy:
          name: Deploy
          command: |
            if [ "$PREVIEW" == "true" ]
            then
              npm run deploy -- --confirm --preview
            else
              npm run deploy -- --confirm
            fi
